import { MigrationInterface, QueryRunner } from "typeorm";

export class CreatePracticesTables1763621992929 implements MigrationInterface {
    name = 'CreatePracticesTables1763621992929'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "quiz_questions" DROP CONSTRAINT "FK_quiz_questions_content"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP CONSTRAINT "FK_reading_quizzes_contents"`);
        await queryRunner.query(`ALTER TABLE "reading_contents" DROP CONSTRAINT "FK_reading_contents_chapter"`);
        await queryRunner.query(`ALTER TABLE "user_progress" DROP CONSTRAINT "FK_user_progress_reading_chapter"`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP CONSTRAINT "FK_approval_evaluations_student_id"`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP CONSTRAINT "FK_approval_evaluations_chapter_id"`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP CONSTRAINT "FK_approval_evaluations_rule_id"`);
        await queryRunner.query(`ALTER TABLE "approval_metrics" DROP CONSTRAINT "FK_approval_metrics_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_quiz_questions_contentId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_quiz_questions_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reading_quizzes_contentId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reading_contents_chapterId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reading_chapters_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_reading_chapters_level"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f93fb77effff1b1afa22b7ada"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_progress_readingChapterId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_rules_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_rules_chapter_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_evaluations_student_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_evaluations_chapter_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_evaluations_evaluated_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_evaluations_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_evaluations_user_chapter_attempt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_metrics_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_metrics_chapter_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_metrics_metric_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_approval_metrics_recorded_at"`);
        await queryRunner.query(`CREATE TYPE "public"."practice_sessions_practice_type_enum" AS ENUM('vocabulary', 'quiz', 'reading', 'interview')`);
        await queryRunner.query(`CREATE TYPE "public"."practice_sessions_status_enum" AS ENUM('started', 'in_progress', 'completed', 'abandoned')`);
        await queryRunner.query(`CREATE TABLE "practice_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "chapter_id" uuid, "practice_type" "public"."practice_sessions_practice_type_enum" NOT NULL, "status" "public"."practice_sessions_status_enum" NOT NULL DEFAULT 'started', "score" numeric(5,2) NOT NULL DEFAULT '0', "progress" numeric(5,2) NOT NULL DEFAULT '0', "max_score" numeric(5,2), "started_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, "duration_seconds" integer, "time_spent_seconds" integer NOT NULL DEFAULT '0', "extra_data" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_70d97b1cdd66f9b01bd492b92fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_df1dc0293865ac941d970b5f70" ON "practice_sessions" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c551b2e1af453dfe01bbb980c" ON "practice_sessions" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7203fe947ee13197999445757b" ON "practice_sessions" ("chapter_id", "practice_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_4220575b03019997afe264ab58" ON "practice_sessions" ("user_id", "practice_type") `);
        await queryRunner.query(`CREATE TABLE "vocabulary_practices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "words_studied" integer NOT NULL DEFAULT '0', "words_learned" integer NOT NULL DEFAULT '0', "correct_answers" integer NOT NULL DEFAULT '0', "total_attempts" integer NOT NULL DEFAULT '0', "last_word_studied" character varying(255), "words_reviewed" integer NOT NULL DEFAULT '0', "streak_count" integer NOT NULL DEFAULT '0', "difficulty_level" character varying(50), "current_word_index" integer NOT NULL DEFAULT '0', "studied_words" json, "reviewed_words" integer NOT NULL DEFAULT '0', "incorrect_answers" integer NOT NULL DEFAULT '0', "practice_session_id" uuid, CONSTRAINT "REL_a8a6b98e2c4ffe6e7642cb7433" UNIQUE ("practice_session_id"), CONSTRAINT "PK_efb2102aa1495d7a412dca2f9cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reading_practices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text_id" character varying(255), "text_title" character varying(500), "total_words" integer NOT NULL DEFAULT '0', "words_read" integer NOT NULL DEFAULT '0', "reading_speed_wpm" numeric(8,2), "comprehension_questions_total" integer NOT NULL DEFAULT '0', "comprehension_questions_correct" integer NOT NULL DEFAULT '0', "reading_time_seconds" integer NOT NULL DEFAULT '0', "difficulty_level" character varying(50), "text_category" character varying(100), "last_position" integer NOT NULL DEFAULT '0', "bookmarks" json, "vocabulary_encountered" json, "practice_session_id" uuid, CONSTRAINT "REL_cca15aba816690c894499fc041" UNIQUE ("practice_session_id"), CONSTRAINT "PK_4c843e77cb8e0fc20b20954ffae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quiz_practices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "total_questions" integer NOT NULL DEFAULT '0', "questions_answered" integer NOT NULL DEFAULT '0', "correct_answers" integer NOT NULL DEFAULT '0', "wrong_answers" integer NOT NULL DEFAULT '0', "last_question_index" integer NOT NULL DEFAULT '0', "average_time_per_question" numeric(8,2), "quiz_category" character varying(100), "difficulty_level" character varying(50), "time_per_question" json, "question_results" json, "practice_session_id" uuid, CONSTRAINT "REL_b0feb5b5e96f90de30318d49ea" UNIQUE ("practice_session_id"), CONSTRAINT "PK_cbcfd4790c0d66d9bf47ab6fe0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "reading_content_id"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "total_questions"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "passing_score"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "time_limit"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "readingContentId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "totalQuestions" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "passingScore" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "timeLimit" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reading_contents" DROP COLUMN "level"`);
        await queryRunner.query(`CREATE TYPE "public"."reading_contents_level_enum" AS ENUM('BASIC', 'INTERMEDIATE', 'ADVANCED')`);
        await queryRunner.query(`ALTER TABLE "reading_contents" ADD "level" "public"."reading_contents_level_enum" NOT NULL DEFAULT 'BASIC'`);
        await queryRunner.query(`ALTER TABLE "reading_chapters" DROP COLUMN "level"`);
        await queryRunner.query(`CREATE TYPE "public"."reading_chapters_level_enum" AS ENUM('1', '2', '3')`);
        await queryRunner.query(`ALTER TABLE "reading_chapters" ADD "level" "public"."reading_chapters_level_enum" NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "approval_rules" ALTER COLUMN "name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approval_rules" ALTER COLUMN "minScoreThreshold" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approval_rules" ALTER COLUMN "isActive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ALTER COLUMN "score" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ALTER COLUMN "threshold" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."approval_evaluations_status_enum" AS ENUM('approved', 'rejected', 'pending')`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD "status" "public"."approval_evaluations_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ALTER COLUMN "evaluatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "approval_metrics" ALTER COLUMN "recordedAt" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_9e7280782ed40e7a6039582a0f" ON "quiz_questions" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_bb87160f74d49831891d86968c" ON "quiz_questions" ("readingContentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9adea68ebecac56b340b453ee" ON "reading_quizzes" ("readingContentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1d3d55f0542eac51dc005be7c" ON "reading_contents" ("readingChapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_091ba38278791eb870605a3924" ON "reading_chapters" ("level") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_941f6f11982a674036ce32a717" ON "reading_chapters" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e444473684e718a80cc0937e5" ON "user_progress" ("readingChapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4020b51fc436a5c1d0b1b898b" ON "approval_rules" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_dcf2dbb20f403f869ddc424e58" ON "approval_rules" ("chapterId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_43918c5975957bae787303999e" ON "approval_evaluations" ("userId", "chapterId", "attemptNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1ea0f1ee80e6a37fdf6dbc61e" ON "approval_evaluations" ("evaluatedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4dc13482a3a891fa6d6d3224d" ON "approval_evaluations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b878b92d3a7f51c4469f941fdd" ON "approval_evaluations" ("chapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_52499f55299e0a0c5096cc3c1f" ON "approval_evaluations" ("ruleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9f92568466186917006071905" ON "approval_evaluations" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d656db4ec57f114457b6361e1a" ON "approval_metrics" ("userId", "chapterId", "metricType") `);
        await queryRunner.query(`CREATE INDEX "IDX_4927b771de34ba4aeb6a2011c2" ON "approval_metrics" ("recordedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9d10914218827f5ad00327af9" ON "approval_metrics" ("metricType") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e7ca55846b03c5cba88c7e205" ON "approval_metrics" ("chapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_842e87c4cf6f39313a7a8851a8" ON "approval_metrics" ("userId") `);
        await queryRunner.query(`ALTER TABLE "quiz_questions" ADD CONSTRAINT "FK_bb87160f74d49831891d86968cb" FOREIGN KEY ("readingContentId") REFERENCES "reading_contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD CONSTRAINT "FK_c9adea68ebecac56b340b453ee5" FOREIGN KEY ("readingContentId") REFERENCES "reading_contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reading_contents" ADD CONSTRAINT "FK_f1d3d55f0542eac51dc005be7ce" FOREIGN KEY ("readingChapterId") REFERENCES "reading_chapters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_progress" ADD CONSTRAINT "FK_1e444473684e718a80cc0937e51" FOREIGN KEY ("readingChapterId") REFERENCES "reading_chapters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD CONSTRAINT "FK_f9f92568466186917006071905a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD CONSTRAINT "FK_52499f55299e0a0c5096cc3c1fb" FOREIGN KEY ("ruleId") REFERENCES "approval_rules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_metrics" ADD CONSTRAINT "FK_842e87c4cf6f39313a7a8851a8e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "practice_sessions" ADD CONSTRAINT "FK_ae16c188d97c26e551a631b19f3" FOREIGN KEY ("chapter_id") REFERENCES "chapters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practices" ADD CONSTRAINT "FK_a8a6b98e2c4ffe6e7642cb74339" FOREIGN KEY ("practice_session_id") REFERENCES "practice_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reading_practices" ADD CONSTRAINT "FK_cca15aba816690c894499fc0413" FOREIGN KEY ("practice_session_id") REFERENCES "practice_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_practices" ADD CONSTRAINT "FK_b0feb5b5e96f90de30318d49ea0" FOREIGN KEY ("practice_session_id") REFERENCES "practice_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "quiz_practices" DROP CONSTRAINT "FK_b0feb5b5e96f90de30318d49ea0"`);
        await queryRunner.query(`ALTER TABLE "reading_practices" DROP CONSTRAINT "FK_cca15aba816690c894499fc0413"`);
        await queryRunner.query(`ALTER TABLE "vocabulary_practices" DROP CONSTRAINT "FK_a8a6b98e2c4ffe6e7642cb74339"`);
        await queryRunner.query(`ALTER TABLE "practice_sessions" DROP CONSTRAINT "FK_ae16c188d97c26e551a631b19f3"`);
        await queryRunner.query(`ALTER TABLE "approval_metrics" DROP CONSTRAINT "FK_842e87c4cf6f39313a7a8851a8e"`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP CONSTRAINT "FK_52499f55299e0a0c5096cc3c1fb"`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP CONSTRAINT "FK_f9f92568466186917006071905a"`);
        await queryRunner.query(`ALTER TABLE "user_progress" DROP CONSTRAINT "FK_1e444473684e718a80cc0937e51"`);
        await queryRunner.query(`ALTER TABLE "reading_contents" DROP CONSTRAINT "FK_f1d3d55f0542eac51dc005be7ce"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP CONSTRAINT "FK_c9adea68ebecac56b340b453ee5"`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" DROP CONSTRAINT "FK_bb87160f74d49831891d86968cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_842e87c4cf6f39313a7a8851a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e7ca55846b03c5cba88c7e205"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9d10914218827f5ad00327af9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4927b771de34ba4aeb6a2011c2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d656db4ec57f114457b6361e1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9f92568466186917006071905"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52499f55299e0a0c5096cc3c1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b878b92d3a7f51c4469f941fdd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4dc13482a3a891fa6d6d3224d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1ea0f1ee80e6a37fdf6dbc61e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43918c5975957bae787303999e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcf2dbb20f403f869ddc424e58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4020b51fc436a5c1d0b1b898b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e444473684e718a80cc0937e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_941f6f11982a674036ce32a717"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_091ba38278791eb870605a3924"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d3d55f0542eac51dc005be7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9adea68ebecac56b340b453ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb87160f74d49831891d86968c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e7280782ed40e7a6039582a0f"`);
        await queryRunner.query(`ALTER TABLE "approval_metrics" ALTER COLUMN "recordedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ALTER COLUMN "evaluatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."approval_evaluations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD "status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ALTER COLUMN "threshold" SET DEFAULT 80.00`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ALTER COLUMN "score" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "approval_rules" ALTER COLUMN "isActive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "approval_rules" ALTER COLUMN "minScoreThreshold" SET DEFAULT 80.00`);
        await queryRunner.query(`ALTER TABLE "approval_rules" ALTER COLUMN "name" SET DEFAULT 'Default Rule'`);
        await queryRunner.query(`ALTER TABLE "reading_chapters" DROP COLUMN "level"`);
        await queryRunner.query(`DROP TYPE "public"."reading_chapters_level_enum"`);
        await queryRunner.query(`ALTER TABLE "reading_chapters" ADD "level" integer NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "reading_contents" DROP COLUMN "level"`);
        await queryRunner.query(`DROP TYPE "public"."reading_contents_level_enum"`);
        await queryRunner.query(`ALTER TABLE "reading_contents" ADD "level" character varying(20) NOT NULL DEFAULT 'BASIC'`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "timeLimit"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "passingScore"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "totalQuestions"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" DROP COLUMN "readingContentId"`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "time_limit" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "passing_score" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "total_questions" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD "reading_content_id" uuid NOT NULL`);
        await queryRunner.query(`DROP TABLE "quiz_practices"`);
        await queryRunner.query(`DROP TABLE "reading_practices"`);
        await queryRunner.query(`DROP TABLE "vocabulary_practices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4220575b03019997afe264ab58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7203fe947ee13197999445757b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c551b2e1af453dfe01bbb980c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df1dc0293865ac941d970b5f70"`);
        await queryRunner.query(`DROP TABLE "practice_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."practice_sessions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."practice_sessions_practice_type_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_approval_metrics_recorded_at" ON "approval_metrics" ("recordedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_metrics_metric_type" ON "approval_metrics" ("metricType") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_metrics_chapter_id" ON "approval_metrics" ("chapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_metrics_user_id" ON "approval_metrics" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_approval_evaluations_user_chapter_attempt" ON "approval_evaluations" ("attemptNumber", "chapterId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_evaluations_status" ON "approval_evaluations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_evaluations_evaluated_at" ON "approval_evaluations" ("evaluatedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_evaluations_chapter_id" ON "approval_evaluations" ("chapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_evaluations_student_id" ON "approval_evaluations" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_rules_chapter_id" ON "approval_rules" ("chapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_approval_rules_active" ON "approval_rules" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_progress_readingChapterId" ON "user_progress" ("readingChapterId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4f93fb77effff1b1afa22b7ada" ON "user_progress" ("chapterId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_reading_chapters_level" ON "reading_chapters" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_reading_chapters_order" ON "reading_chapters" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_reading_contents_chapterId" ON "reading_contents" ("readingChapterId") `);
        await queryRunner.query(`CREATE INDEX "IDX_reading_quizzes_contentId" ON "reading_quizzes" ("reading_content_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_quiz_questions_order" ON "quiz_questions" ("order") `);
        await queryRunner.query(`CREATE INDEX "IDX_quiz_questions_contentId" ON "quiz_questions" ("readingContentId") `);
        await queryRunner.query(`ALTER TABLE "approval_metrics" ADD CONSTRAINT "FK_approval_metrics_user_id" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD CONSTRAINT "FK_approval_evaluations_rule_id" FOREIGN KEY ("ruleId") REFERENCES "approval_rules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD CONSTRAINT "FK_approval_evaluations_chapter_id" FOREIGN KEY ("chapterId") REFERENCES "chapters"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_evaluations" ADD CONSTRAINT "FK_approval_evaluations_student_id" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_progress" ADD CONSTRAINT "FK_user_progress_reading_chapter" FOREIGN KEY ("readingChapterId") REFERENCES "reading_chapters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reading_contents" ADD CONSTRAINT "FK_reading_contents_chapter" FOREIGN KEY ("readingChapterId") REFERENCES "reading_chapters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reading_quizzes" ADD CONSTRAINT "FK_reading_quizzes_contents" FOREIGN KEY ("reading_content_id") REFERENCES "reading_contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" ADD CONSTRAINT "FK_quiz_questions_content" FOREIGN KEY ("readingContentId") REFERENCES "reading_contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
